### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

### ISSUE THREAD

**Issue by Xysma** [iskandarjamil/convert-html-to-js#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [convert-html-to-js](https://github.com/iskandarjamil/convert-html-to-js) package 1.0.3

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

```
At C:\Users\Butcher\.atom\packages\convert-html-to-js\lib\convert-html-to-js.js:34

TypeError: Cannot read property 'getSelectedText' of undefined
    at Object.convertArray (/packages/convert-html-to-js/lib/convert-html-to-js.js:34:40)
    at /packages/convert-html-to-js/lib/convert-html-to-js.js:9:54)
    at CommandRegistry.handleCommandEvent (C:/ProgramData/Butcher/atom/app-1.30.0/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (C:/ProgramData/Butcher/atom/app-1.30.0/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (C:/ProgramData/Butcher/atom/app-1.30.0/resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (C:/ProgramData/Butcher/atom/app-1.30.0/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  3x -2:11.2.0 tree-view:toggle-focus (div.tool-panel.tree-view)
     -1:42.8.0 application:open-file (ul.list-inline.tab-bar.inset-panel)
     -0:28 html-to-javascript:convert-array (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
atom-css-comb 3.3.1 
atom-html5-boilerplate 0.2.0 
convert-html-to-js 1.0.3 
es6-javascript 1.0.0 
html-helper 0.2.3 
html-to-css 0.2.2 
html-wrapper 0.2.0 
language-html5-subtlegradient 0.1.0 
```

**Comment by iskandar-j** [comment]
@Xysma Please make a selection where you like to convert, and then run the command.
If you like to convert the whole file, please select all then run the command.
